wordpress:
   image: wordpress:latest
   links:
      - wordpress_db:mysql
   ports:
      - 80:80
   volumes:
      - ./code:/code
      - ./html:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

wordpress_db:
   image: mariadb
   environment: 
      MYSQL_ROOT_PASSWORD: Pa55w0rd123
      MYSQL_DATABASE: wordpress
   volumes:
      - ./database:/var/lib/mysql
